// generate-sitemap.js
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ==================== YOUR COMPLETE INDIA_LOCATIONS DATA ====================
// (Copy all your INDIA_LOCATIONS from App.jsx - all 700+ cities)

const INDIA_LOCATIONS = [
  ["anantapur","Anantapur","Andhra Pradesh"],
  ["chittoor","Chittoor","Andhra Pradesh"],
  ["east-godavari","East Godavari","Andhra Pradesh"],
  ["guntur","Guntur","Andhra Pradesh"],
  ["kadapa","Kadapa","Andhra Pradesh"],
  ["krishna","Krishna","Andhra Pradesh"],
  ["kurnool","Kurnool","Andhra Pradesh"],
  ["nellore","Nellore","Andhra Pradesh"],
  ["prakasam","Prakasam","Andhra Pradesh"],
  ["srikakulam","Srikakulam","Andhra Pradesh"],
  ["visakhapatnam","Visakhapatnam","Andhra Pradesh"],
  ["vizianagaram","Vizianagaram","Andhra Pradesh"],
  ["west-godavari","West Godavari","Andhra Pradesh"],
  ["tirupati","Tirupati","Andhra Pradesh"],
  ["vijayawada","Vijayawada","Andhra Pradesh"],
  ["kakinada","Kakinada","Andhra Pradesh"],
  ["rajahmundry","Rajahmundry","Andhra Pradesh"],
  ["nandyal","Nandyal","Andhra Pradesh"],
  ["ongole","Ongole","Andhra Pradesh"],
  ["eluru","Eluru","Andhra Pradesh"],
  ["bapatla","Bapatla","Andhra Pradesh"],
  ["parvathipuram-manyam","Parvathipuram Manyam","Andhra Pradesh"],
  ["alluri-sitharama-raju","Alluri Sitharama Raju","Andhra Pradesh"],
  ["anakapalli","Anakapalli","Andhra Pradesh"],
  ["konaseema","Konaseema","Andhra Pradesh"],
  ["sri-sathya-sai","Sri Sathya Sai","Andhra Pradesh"],
  ["anjaw","Anjaw","Arunachal Pradesh"],
  ["changlang","Changlang","Arunachal Pradesh"],
  ["dibang-valley","Dibang Valley","Arunachal Pradesh"],
  ["east-kameng","East Kameng","Arunachal Pradesh"],
  ["east-siang","East Siang","Arunachal Pradesh"],
  ["itanagar","Itanagar","Arunachal Pradesh"],
  ["kamle","Kamle","Arunachal Pradesh"],
  ["kra-daadi","Kra Daadi","Arunachal Pradesh"],
  ["kurung-kumey","Kurung Kumey","Arunachal Pradesh"],
  ["lepa-rada","Lepa Rada","Arunachal Pradesh"],
  ["lohit","Lohit","Arunachal Pradesh"],
  ["longding","Longding","Arunachal Pradesh"],
  ["lower-dibang-valley","Lower Dibang Valley","Arunachal Pradesh"],
  ["lower-siang","Lower Siang","Arunachal Pradesh"],
  ["lower-subansiri","Lower Subansiri","Arunachal Pradesh"],
  ["namsai","Namsai","Arunachal Pradesh"],
  ["pakke-kessang","Pakke Kessang","Arunachal Pradesh"],
  ["papum-pare","Papum Pare","Arunachal Pradesh"],
  ["shi-yomi","Shi Yomi","Arunachal Pradesh"],
  ["siang","Siang","Arunachal Pradesh"],
  ["tawang","Tawang","Arunachal Pradesh"],
  ["tirap","Tirap","Arunachal Pradesh"],
  ["upper-dibang-valley","Upper Dibang Valley","Arunachal Pradesh"],
  ["upper-siang","Upper Siang","Arunachal Pradesh"],
  ["upper-subansiri","Upper Subansiri","Arunachal Pradesh"],
  ["west-kameng","West Kameng","Arunachal Pradesh"],
  ["west-siang","West Siang","Arunachal Pradesh"],
  ["baksa","Baksa","Assam"],
  ["barpeta","Barpeta","Assam"],
  ["biswanath","Biswanath","Assam"],
  ["bongaigaon","Bongaigaon","Assam"],
  ["cachar","Cachar","Assam"],
  ["charaideo","Charaideo","Assam"],
  ["chirang","Chirang","Assam"],
  ["darrang","Darrang","Assam"],
  ["dhemaji","Dhemaji","Assam"],
  ["dhubri","Dhubri","Assam"],
  ["dibrugarh","Dibrugarh","Assam"],
  ["dima-hasao","Dima Hasao","Assam"],
  ["goalpara","Goalpara","Assam"],
  ["golaghat","Golaghat","Assam"],
  ["guwahati","Guwahati","Assam"],
  ["hailakandi","Hailakandi","Assam"],
  ["hojai","Hojai","Assam"],
  ["jorhat","Jorhat","Assam"],
  ["kamrup","Kamrup","Assam"],
  ["kamrup-metropolitan","Kamrup Metropolitan","Assam"],
  ["karbi-anglong","Karbi Anglong","Assam"],
  ["karimganj","Karimganj","Assam"],
  ["kokrajhar","Kokrajhar","Assam"],
  ["lakhimpur","Lakhimpur","Assam"],
  ["majuli","Majuli","Assam"],
  ["morigaon","Morigaon","Assam"],
  ["nagaon","Nagaon","Assam"],
  ["nalbari","Nalbari","Assam"],
  ["sivasagar","Sivasagar","Assam"],
  ["silchar","Silchar","Assam"],
  ["sonitpur","Sonitpur","Assam"],
  ["south-salmara-mankachar","South Salmara Mankachar","Assam"],
  ["tinsukia","Tinsukia","Assam"],
  ["udalguri","Udalguri","Assam"],
  ["west-karbi-anglong","West Karbi Anglong","Assam"],
  ["araria","Araria","Bihar"],
  ["arwal","Arwal","Bihar"],
  ["aurangabad","Aurangabad","Bihar"],
  ["banka","Banka","Bihar"],
  ["begusarai","Begusarai","Bihar"],
  ["bhagalpur","Bhagalpur","Bihar"],
  ["bhojpur","Bhojpur","Bihar"],
  ["buxar","Buxar","Bihar"],
  ["darbhanga","Darbhanga","Bihar"],
  ["east-champaran","East Champaran","Bihar"],
  ["gaya","Gaya","Bihar"],
  ["gopalganj","Gopalganj","Bihar"],
  ["jamui","Jamui","Bihar"],
  ["jehanabad","Jehanabad","Bihar"],
  ["kaimur","Kaimur","Bihar"],
  ["katihar","Katihar","Bihar"],
  ["khagaria","Khagaria","Bihar"],
  ["kishanganj","Kishanganj","Bihar"],
  ["lakhisarai","Lakhisarai","Bihar"],
  ["madhepura","Madhepura","Bihar"],
  ["madhubani","Madhubani","Bihar"],
  ["munger","Munger","Bihar"],
  ["muzaffarpur","Muzaffarpur","Bihar"],
  ["nalanda","Nalanda","Bihar"],
  ["nawada","Nawada","Bihar"],
  ["patna","Patna","Bihar"],
  ["purnia","Purnia","Bihar"],
  ["rohtas","Rohtas","Bihar"],
  ["saharsa","Saharsa","Bihar"],
  ["samastipur","Samastipur","Bihar"],
  ["saran","Saran","Bihar"],
  ["sheikhpura","Sheikhpura","Bihar"],
  ["sheohar","Sheohar","Bihar"],
  ["sitamarhi","Sitamarhi","Bihar"],
  ["siwan","Siwan","Bihar"],
  ["supaul","Supaul","Bihar"],
  ["vaishali","Vaishali","Bihar"],
  ["west-champaran","West Champaran","Bihar"],
  ["balod","Balod","Chhattisgarh"],
  ["baloda-bazar","Baloda Bazar","Chhattisgarh"],
  ["balrampur","Balrampur","Chhattisgarh"],
  ["bastar","Bastar","Chhattisgarh"],
  ["bemetara","Bemetara","Chhattisgarh"],
  ["bijapur","Bijapur","Chhattisgarh"],
  ["bilaspur","Bilaspur","Chhattisgarh"],
  ["dantewada","Dantewada","Chhattisgarh"],
  ["dhamtari","Dhamtari","Chhattisgarh"],
  ["durg","Durg","Chhattisgarh"],
  ["gariaband","Gariaband","Chhattisgarh"],
  ["gaurela-pendra-marwahi","Gaurela Pendra Marwahi","Chhattisgarh"],
  ["janjgir-champa","Janjgir Champa","Chhattisgarh"],
  ["jashpur","Jashpur","Chhattisgarh"],
  ["kabirdham","Kabirdham","Chhattisgarh"],
  ["kanker","Kanker","Chhattisgarh"],
  ["khairagarh","Khairagarh","Chhattisgarh"],
  ["kondagaon","Kondagaon","Chhattisgarh"],
  ["korba","Korba","Chhattisgarh"],
  ["koriya","Koriya","Chhattisgarh"],
  ["mahasamund","Mahasamund","Chhattisgarh"],
  ["manendragarh","Manendragarh","Chhattisgarh"],
  ["mohla-manpur","Mohla Manpur","Chhattisgarh"],
  ["mungeli","Mungeli","Chhattisgarh"],
  ["narayanpur","Narayanpur","Chhattisgarh"],
  ["raigarh","Raigarh","Chhattisgarh"],
  ["raipur","Raipur","Chhattisgarh"],
  ["rajnandgaon","Rajnandgaon","Chhattisgarh"],
  ["sakti","Sakti","Chhattisgarh"],
  ["sarangarh-bilaigarh","Sarangarh Bilaigarh","Chhattisgarh"],
  ["sukma","Sukma","Chhattisgarh"],
  ["surajpur","Surajpur","Chhattisgarh"],
  ["surguja","Surguja","Chhattisgarh"],
  ["north-goa","North Goa","Goa"],
  ["south-goa","South Goa","Goa"],
  ["ahmedabad","Ahmedabad","Gujarat"],
  ["amreli","Amreli","Gujarat"],
  ["anand","Anand","Gujarat"],
  ["aravalli","Aravalli","Gujarat"],
  ["banaskantha","Banaskantha","Gujarat"],
  ["bharuch","Bharuch","Gujarat"],
  ["bhavnagar","Bhavnagar","Gujarat"],
  ["botad","Botad","Gujarat"],
  ["chhota-udaipur","Chhota Udaipur","Gujarat"],
  ["dahod","Dahod","Gujarat"],
  ["dang","Dang","Gujarat"],
  ["devbhoomi-dwarka","Devbhoomi Dwarka","Gujarat"],
  ["gandhinagar","Gandhinagar","Gujarat"],
  ["gir-somnath","Gir Somnath","Gujarat"],
  ["jamnagar","Jamnagar","Gujarat"],
  ["junagadh","Junagadh","Gujarat"],
  ["kheda","Kheda","Gujarat"],
  ["kutch","Kutch","Gujarat"],
  ["mahisagar","Mahisagar","Gujarat"],
  ["mehsana","Mehsana","Gujarat"],
  ["morbi","Morbi","Gujarat"],
  ["narmada","Narmada","Gujarat"],
  ["navsari","Navsari","Gujarat"],
  ["panchmahal","Panchmahal","Gujarat"],
  ["patan","Patan","Gujarat"],
  ["porbandar","Porbandar","Gujarat"],
  ["rajkot","Rajkot","Gujarat"],
  ["sabarkantha","Sabarkantha","Gujarat"],
  ["surat","Surat","Gujarat"],
  ["surendranagar","Surendranagar","Gujarat"],
  ["tapi","Tapi","Gujarat"],
  ["vadodara","Vadodara","Gujarat"],
  ["valsad","Valsad","Gujarat"],
  ["ambala","Ambala","Haryana"],
  ["bhiwani","Bhiwani","Haryana"],
  ["charkhi-dadri","Charkhi Dadri","Haryana"],
  ["faridabad","Faridabad","Haryana"],
  ["fatehabad","Fatehabad","Haryana"],
  ["gurugram","Gurugram","Haryana"],
  ["hisar","Hisar","Haryana"],
  ["jhajjar","Jhajjar","Haryana"],
  ["jind","Jind","Haryana"],
  ["kaithal","Kaithal","Haryana"],
  ["karnal","Karnal","Haryana"],
  ["kurukshetra","Kurukshetra","Haryana"],
  ["mahendragarh","Mahendragarh","Haryana"],
  ["nuh","Nuh","Haryana"],
  ["palwal","Palwal","Haryana"],
  ["panchkula","Panchkula","Haryana"],
  ["panipat","Panipat","Haryana"],
  ["rewari","Rewari","Haryana"],
  ["rohtak","Rohtak","Haryana"],
  ["sirsa","Sirsa","Haryana"],
  ["sonipat","Sonipat","Haryana"],
  ["yamunanagar","Yamunanagar","Haryana"],
  ["bilaspur-hp","Bilaspur","Himachal Pradesh"],
  ["chamba","Chamba","Himachal Pradesh"],
  ["hamirpur-hp","Hamirpur","Himachal Pradesh"],
  ["kangra","Kangra","Himachal Pradesh"],
  ["kinnaur","Kinnaur","Himachal Pradesh"],
  ["kullu","Kullu","Himachal Pradesh"],
  ["lahaul-spiti","Lahaul Spiti","Himachal Pradesh"],
  ["mandi","Mandi","Himachal Pradesh"],
  ["shimla","Shimla","Himachal Pradesh"],
  ["sirmaur","Sirmaur","Himachal Pradesh"],
  ["solan","Solan","Himachal Pradesh"],
  ["una","Una","Himachal Pradesh"],
  ["bokaro","Bokaro","Jharkhand"],
  ["chatra","Chatra","Jharkhand"],
  ["deoghar","Deoghar","Jharkhand"],
  ["dhanbad","Dhanbad","Jharkhand"],
  ["dumka","Dumka","Jharkhand"],
  ["east-singhbhum","East Singhbhum","Jharkhand"],
  ["garhwa","Garhwa","Jharkhand"],
  ["giridih","Giridih","Jharkhand"],
  ["godda","Godda","Jharkhand"],
  ["gumla","Gumla","Jharkhand"],
  ["hazaribagh","Hazaribagh","Jharkhand"],
  ["jamtara","Jamtara","Jharkhand"],
  ["jamshedpur","Jamshedpur","Jharkhand"],
  ["khunti","Khunti","Jharkhand"],
  ["koderma","Koderma","Jharkhand"],
  ["latehar","Latehar","Jharkhand"],
  ["lohardaga","Lohardaga","Jharkhand"],
  ["pakur","Pakur","Jharkhand"],
  ["palamu","Palamu","Jharkhand"],
  ["ramgarh","Ramgarh","Jharkhand"],
  ["ranchi","Ranchi","Jharkhand"],
  ["sahebganj","Sahebganj","Jharkhand"],
  ["seraikela-kharsawan","Seraikela Kharsawan","Jharkhand"],
  ["simdega","Simdega","Jharkhand"],
  ["west-singhbhum","West Singhbhum","Jharkhand"],
  ["bagalkot","Bagalkot","Karnataka"],
  ["bangalore-rural","Bangalore Rural","Karnataka"],
  ["bangalore-urban","Bangalore Urban","Karnataka"],
  ["belgaum","Belgaum","Karnataka"],
  ["bellary","Bellary","Karnataka"],
  ["bidar","Bidar","Karnataka"],
  ["chamarajanagar","Chamarajanagar","Karnataka"],
  ["chikballapur","Chikballapur","Karnataka"],
  ["chikkamagaluru","Chikkamagaluru","Karnataka"],
  ["chitradurga","Chitradurga","Karnataka"],
  ["dakshina-kannada","Dakshina Kannada","Karnataka"],
  ["davangere","Davangere","Karnataka"],
  ["dharwad","Dharwad","Karnataka"],
  ["gadag","Gadag","Karnataka"],
  ["gulbarga","Gulbarga","Karnataka"],
  ["hassan","Hassan","Karnataka"],
  ["haveri","Haveri","Karnataka"],
  ["kodagu","Kodagu","Karnataka"],
  ["kolar","Kolar","Karnataka"],
  ["koppal","Koppal","Karnataka"],
  ["mandya","Mandya","Karnataka"],
  ["mangalore","Mangalore","Karnataka"],
  ["mysore","Mysore","Karnataka"],
  ["raichur","Raichur","Karnataka"],
  ["ramanagara","Ramanagara","Karnataka"],
  ["shimoga","Shimoga","Karnataka"],
  ["tumkur","Tumkur","Karnataka"],
  ["udupi","Udupi","Karnataka"],
  ["uttara-kannada","Uttara Kannada","Karnataka"],
  ["vijayapura","Vijayapura","Karnataka"],
  ["yadgir","Yadgir","Karnataka"],
  ["alappuzha","Alappuzha","Kerala"],
  ["ernakulam","Ernakulam","Kerala"],
  ["idukki","Idukki","Kerala"],
  ["kannur","Kannur","Kerala"],
  ["kasaragod","Kasaragod","Kerala"],
  ["kochi","Kochi","Kerala"],
  ["kollam","Kollam","Kerala"],
  ["kottayam","Kottayam","Kerala"],
  ["kozhikode","Kozhikode","Kerala"],
  ["malappuram","Malappuram","Kerala"],
  ["palakkad","Palakkad","Kerala"],
  ["pathanamthitta","Pathanamthitta","Kerala"],
  ["thiruvananthapuram","Thiruvananthapuram","Kerala"],
  ["thrissur","Thrissur","Kerala"],
  ["wayanad","Wayanad","Kerala"],
  ["agar-malwa","Agar Malwa","Madhya Pradesh"],
  ["alirajpur","Alirajpur","Madhya Pradesh"],
  ["anuppur","Anuppur","Madhya Pradesh"],
  ["ashoknagar","Ashoknagar","Madhya Pradesh"],
  ["balaghat","Balaghat","Madhya Pradesh"],
  ["barwani","Barwani","Madhya Pradesh"],
  ["betul","Betul","Madhya Pradesh"],
  ["bhind","Bhind","Madhya Pradesh"],
  ["bhopal","Bhopal","Madhya Pradesh"],
  ["burhanpur","Burhanpur","Madhya Pradesh"],
  ["chhatarpur","Chhatarpur","Madhya Pradesh"],
  ["chhindwara","Chhindwara","Madhya Pradesh"],
  ["damoh","Damoh","Madhya Pradesh"],
  ["datia","Datia","Madhya Pradesh"],
  ["dewas","Dewas","Madhya Pradesh"],
  ["dhar","Dhar","Madhya Pradesh"],
  ["dindori","Dindori","Madhya Pradesh"],
  ["guna","Guna","Madhya Pradesh"],
  ["gwalior","Gwalior","Madhya Pradesh"],
  ["harda","Harda","Madhya Pradesh"],
  ["hoshangabad","Hoshangabad","Madhya Pradesh"],
  ["indore","Indore","Madhya Pradesh"],
  ["jabalpur","Jabalpur","Madhya Pradesh"],
  ["jhabua","Jhabua","Madhya Pradesh"],
  ["katni","Katni","Madhya Pradesh"],
  ["khandwa","Khandwa","Madhya Pradesh"],
  ["khargone","Khargone","Madhya Pradesh"],
  ["mandla","Mandla","Madhya Pradesh"],
  ["mandsaur","Mandsaur","Madhya Pradesh"],
  ["morena","Morena","Madhya Pradesh"],
  ["narsinghpur","Narsinghpur","Madhya Pradesh"],
  ["neemuch","Neemuch","Madhya Pradesh"],
  ["niwari","Niwari","Madhya Pradesh"],
  ["panna","Panna","Madhya Pradesh"],
  ["raisen","Raisen","Madhya Pradesh"],
  ["rajgarh","Rajgarh","Madhya Pradesh"],
  ["ratlam","Ratlam","Madhya Pradesh"],
  ["rewa","Rewa","Madhya Pradesh"],
  ["sagar","Sagar","Madhya Pradesh"],
  ["satna","Satna","Madhya Pradesh"],
  ["sehore","Sehore","Madhya Pradesh"],
  ["seoni","Seoni","Madhya Pradesh"],
  ["shahdol","Shahdol","Madhya Pradesh"],
  ["shajapur","Shajapur","Madhya Pradesh"],
  ["sheopur","Sheopur","Madhya Pradesh"],
  ["shivpuri","Shivpuri","Madhya Pradesh"],
  ["sidhi","Sidhi","Madhya Pradesh"],
  ["singrauli","Singrauli","Madhya Pradesh"],
  ["tikamgarh","Tikamgarh","Madhya Pradesh"],
  ["ujjain","Ujjain","Madhya Pradesh"],
  ["umaria","Umaria","Madhya Pradesh"],
  ["vidisha","Vidisha","Madhya Pradesh"],
  ["ahmednagar","Ahmednagar","Maharashtra"],
  ["akola","Akola","Maharashtra"],
  ["amravati","Amravati","Maharashtra"],
  ["beed","Beed","Maharashtra"],
  ["bhandara","Bhandara","Maharashtra"],
  ["buldhana","Buldhana","Maharashtra"],
  ["chandrapur","Chandrapur","Maharashtra"],
  ["dhule","Dhule","Maharashtra"],
  ["gadchiroli","Gadchiroli","Maharashtra"],
  ["gondia","Gondia","Maharashtra"],
  ["hingoli","Hingoli","Maharashtra"],
  ["jalgaon","Jalgaon","Maharashtra"],
  ["jalna","Jalna","Maharashtra"],
  ["kolhapur","Kolhapur","Maharashtra"],
  ["latur","Latur","Maharashtra"],
  ["mumbai-city","Mumbai City","Maharashtra"],
  ["mumbai-suburban","Mumbai Suburban","Maharashtra"],
  ["nagpur","Nagpur","Maharashtra"],
  ["nanded","Nanded","Maharashtra"],
  ["nandurbar","Nandurbar","Maharashtra"],
  ["nashik","Nashik","Maharashtra"],
  ["osmanabad","Osmanabad","Maharashtra"],
  ["palghar","Palghar","Maharashtra"],
  ["parbhani","Parbhani","Maharashtra"],
  ["pune","Pune","Maharashtra"],
  ["raigad","Raigad","Maharashtra"],
  ["ratnagiri","Ratnagiri","Maharashtra"],
  ["sangli","Sangli","Maharashtra"],
  ["satara","Satara","Maharashtra"],
  ["sindhudurg","Sindhudurg","Maharashtra"],
  ["solapur","Solapur","Maharashtra"],
  ["thane","Thane","Maharashtra"],
  ["wardha","Wardha","Maharashtra"],
  ["washim","Washim","Maharashtra"],
  ["yavatmal","Yavatmal","Maharashtra"],
  ["bishnupur","Bishnupur","Manipur"],
  ["chandel","Chandel","Manipur"],
  ["churachandpur","Churachandpur","Manipur"],
  ["imphal-east","Imphal East","Manipur"],
  ["imphal-west","Imphal West","Manipur"],
  ["jiribam","Jiribam","Manipur"],
  ["kakching","Kakching","Manipur"],
  ["kamjong","Kamjong","Manipur"],
  ["kangpokpi","Kangpokpi","Manipur"],
  ["noney","Noney","Manipur"],
  ["pherzawl","Pherzawl","Manipur"],
  ["senapati","Senapati","Manipur"],
  ["tamenglong","Tamenglong","Manipur"],
  ["tengnoupal","Tengnoupal","Manipur"],
  ["thoubal","Thoubal","Manipur"],
  ["ukhrul","Ukhrul","Manipur"],
  ["east-garo-hills","East Garo Hills","Meghalaya"],
  ["east-jaintia-hills","East Jaintia Hills","Meghalaya"],
  ["east-khasi-hills","East Khasi Hills","Meghalaya"],
  ["eastern-west-khasi-hills","Eastern West Khasi Hills","Meghalaya"],
  ["north-garo-hills","North Garo Hills","Meghalaya"],
  ["ri-bhoi","Ri Bhoi","Meghalaya"],
  ["shillong","Shillong","Meghalaya"],
  ["south-garo-hills","South Garo Hills","Meghalaya"],
  ["south-west-garo-hills","South West Garo Hills","Meghalaya"],
  ["south-west-khasi-hills","South West Khasi Hills","Meghalaya"],
  ["west-garo-hills","West Garo Hills","Meghalaya"],
  ["west-jaintia-hills","West Jaintia Hills","Meghalaya"],
  ["west-khasi-hills","West Khasi Hills","Meghalaya"],
  ["aizawl","Aizawl","Mizoram"],
  ["champhai","Champhai","Mizoram"],
  ["hnahthial","Hnahthial","Mizoram"],
  ["khawzawl","Khawzawl","Mizoram"],
  ["kolasib","Kolasib","Mizoram"],
  ["lawngtlai","Lawngtlai","Mizoram"],
  ["lunglei","Lunglei","Mizoram"],
  ["mamit","Mamit","Mizoram"],
  ["saitual","Saitual","Mizoram"],
  ["serchhip","Serchhip","Mizoram"],
  ["siaha","Siaha","Mizoram"],
  ["chumoukedima","Chumoukedima","Nagaland"],
  ["dimapur","Dimapur","Nagaland"],
  ["kiphire","Kiphire","Nagaland"],
  ["kohima","Kohima","Nagaland"],
  ["longleng","Longleng","Nagaland"],
  ["mokokchung","Mokokchung","Nagaland"],
  ["mon","Mon","Nagaland"],
  ["niuland","Niuland","Nagaland"],
  ["noklak","Noklak","Nagaland"],
  ["peren","Peren","Nagaland"],
  ["phek","Phek","Nagaland"],
  ["shamator","Shamator","Nagaland"],
  ["tseminyu","Tseminyu","Nagaland"],
  ["tuensang","Tuensang","Nagaland"],
  ["wokha","Wokha","Nagaland"],
  ["zunheboto","Zunheboto","Nagaland"],
  ["angul","Angul","Odisha"],
  ["balangir","Balangir","Odisha"],
  ["balasore","Balasore","Odisha"],
  ["bargarh","Bargarh","Odisha"],
  ["bhadrak","Bhadrak","Odisha"],
  ["bhubaneswar","Bhubaneswar","Odisha"],
  ["boudh","Boudh","Odisha"],
  ["cuttack","Cuttack","Odisha"],
  ["deogarh","Deogarh","Odisha"],
  ["dhenkanal","Dhenkanal","Odisha"],
  ["gajapati","Gajapati","Odisha"],
  ["ganjam","Ganjam","Odisha"],
  ["jagatsinghpur","Jagatsinghpur","Odisha"],
  ["jajpur","Jajpur","Odisha"],
  ["jharsuguda","Jharsuguda","Odisha"],
  ["kalahandi","Kalahandi","Odisha"],
  ["kandhamal","Kandhamal","Odisha"],
  ["kendrapara","Kendrapara","Odisha"],
  ["kendujhar","Kendujhar","Odisha"],
  ["khordha","Khordha","Odisha"],
  ["koraput","Koraput","Odisha"],
  ["malkangiri","Malkangiri","Odisha"],
  ["mayurbhanj","Mayurbhanj","Odisha"],
  ["nabarangpur","Nabarangpur","Odisha"],
  ["nayagarh","Nayagarh","Odisha"],
  ["nuapada","Nuapada","Odisha"],
  ["puri","Puri","Odisha"],
  ["rayagada","Rayagada","Odisha"],
  ["sambalpur","Sambalpur","Odisha"],
  ["sonepur","Sonepur","Odisha"],
  ["sundargarh","Sundargarh","Odisha"],
  ["amritsar","Amritsar","Punjab"],
  ["barnala","Barnala","Punjab"],
  ["bathinda","Bathinda","Punjab"],
  ["faridkot","Faridkot","Punjab"],
  ["fatehgarh-sahib","Fatehgarh Sahib","Punjab"],
  ["fazilka","Fazilka","Punjab"],
  ["ferozepur","Ferozepur","Punjab"],
  ["gurdaspur","Gurdaspur","Punjab"],
  ["hoshiarpur","Hoshiarpur","Punjab"],
  ["jalandhar","Jalandhar","Punjab"],
  ["kapurthala","Kapurthala","Punjab"],
  ["ludhiana","Ludhiana","Punjab"],
  ["malerkotla","Malerkotla","Punjab"],
  ["mansa","Mansa","Punjab"],
  ["moga","Moga","Punjab"],
  ["mohali","Mohali","Punjab"],
  ["muktsar","Muktsar","Punjab"],
  ["pathankot","Pathankot","Punjab"],
  ["patiala","Patiala","Punjab"],
  ["rupnagar","Rupnagar","Punjab"],
  ["sangrur","Sangrur","Punjab"],
  ["shahid-bhagat-singh-nagar","Shahid Bhagat Singh Nagar","Punjab"],
  ["tarn-taran","Tarn Taran","Punjab"],
  ["ajmer","Ajmer","Rajasthan"],
  ["alwar","Alwar","Rajasthan"],
  ["anupgarh","Anupgarh","Rajasthan"],
  ["balotra","Balotra","Rajasthan"],
  ["banswara","Banswara","Rajasthan"],
  ["baran","Baran","Rajasthan"],
  ["barmer","Barmer","Rajasthan"],
  ["beawar","Beawar","Rajasthan"],
  ["bharatpur","Bharatpur","Rajasthan"],
  ["bhilwara","Bhilwara","Rajasthan"],
  ["bikaner","Bikaner","Rajasthan"],
  ["bundi","Bundi","Rajasthan"],
  ["chittorgarh","Chittorgarh","Rajasthan"],
  ["churu","Churu","Rajasthan"],
  ["dausa","Dausa","Rajasthan"],
  ["deeg","Deeg","Rajasthan"],
  ["dhaulpur","Dhaulpur","Rajasthan"],
  ["didwana-kuchaman","Didwana Kuchaman","Rajasthan"],
  ["dungarpur","Dungarpur","Rajasthan"],
  ["ganganagar","Ganganagar","Rajasthan"],
  ["hanumangarh","Hanumangarh","Rajasthan"],
  ["jaipur","Jaipur","Rajasthan"],
  ["jaipur-rural","Jaipur Rural","Rajasthan"],
  ["jaisalmer","Jaisalmer","Rajasthan"],
  ["jalore","Jalore","Rajasthan"],
  ["jhalawar","Jhalawar","Rajasthan"],
  ["jhunjhunu","Jhunjhunu","Rajasthan"],
  ["jodhpur","Jodhpur","Rajasthan"],
  ["jodhpur-rural","Jodhpur Rural","Rajasthan"],
  ["karauli","Karauli","Rajasthan"],
  ["kekri","Kekri","Rajasthan"],
  ["kota","Kota","Rajasthan"],
  ["kotputli-behror","Kotputli Behror","Rajasthan"],
  ["nagaur","Nagaur","Rajasthan"],
  ["neem-ka-thana","Neem Ka Thana","Rajasthan"],
  ["pali","Pali","Rajasthan"],
  ["phalodi","Phalodi","Rajasthan"],
  ["pratapgarh","Pratapgarh","Rajasthan"],
  ["rajsamand","Rajsamand","Rajasthan"],
  ["salumbar","Salumbar","Rajasthan"],
  ["sanchore","Sanchore","Rajasthan"],
  ["sawai-madhopur","Sawai Madhopur","Rajasthan"],
  ["shahpura","Shahpura","Rajasthan"],
  ["sikar","Sikar","Rajasthan"],
  ["sirohi","Sirohi","Rajasthan"],
  ["tonk","Tonk","Rajasthan"],
  ["udaipur","Udaipur","Rajasthan"],
  ["east-sikkim","East Sikkim","Sikkim"],
  ["gangtok","Gangtok","Sikkim"],
  ["north-sikkim","North Sikkim","Sikkim"],
  ["pakyong","Pakyong","Sikkim"],
  ["soreng","Soreng","Sikkim"],
  ["west-sikkim","West Sikkim","Sikkim"],
  ["ariyalur","Ariyalur","Tamil Nadu"],
  ["chengalpattu","Chengalpattu","Tamil Nadu"],
  ["chennai","Chennai","Tamil Nadu"],
  ["coimbatore","Coimbatore","Tamil Nadu"],
  ["cuddalore","Cuddalore","Tamil Nadu"],
  ["dharmapuri","Dharmapuri","Tamil Nadu"],
  ["dindigul","Dindigul","Tamil Nadu"],
  ["erode","Erode","Tamil Nadu"],
  ["kallakurichi","Kallakurichi","Tamil Nadu"],
  ["kancheepuram","Kancheepuram","Tamil Nadu"],
  ["kanniyakumari","Kanniyakumari","Tamil Nadu"],
  ["karur","Karur","Tamil Nadu"],
  ["krishnagiri","Krishnagiri","Tamil Nadu"],
  ["madurai","Madurai","Tamil Nadu"],
  ["mayiladuthurai","Mayiladuthurai","Tamil Nadu"],
  ["nagapattinam","Nagapattinam","Tamil Nadu"],
  ["namakkal","Namakkal","Tamil Nadu"],
  ["nilgiris","Nilgiris","Tamil Nadu"],
  ["perambalur","Perambalur","Tamil Nadu"],
  ["pudukkottai","Pudukkottai","Tamil Nadu"],
  ["ramanathapuram","Ramanathapuram","Tamil Nadu"],
  ["ranipet","Ranipet","Tamil Nadu"],
  ["salem","Salem","Tamil Nadu"],
  ["sivaganga","Sivaganga","Tamil Nadu"],
  ["tenkasi","Tenkasi","Tamil Nadu"],
  ["thanjavur","Thanjavur","Tamil Nadu"],
  ["theni","Theni","Tamil Nadu"],
  ["thoothukudi","Thoothukudi","Tamil Nadu"],
  ["tiruchirappalli","Tiruchirappalli","Tamil Nadu"],
  ["tirunelveli","Tirunelveli","Tamil Nadu"],
  ["tirupathur","Tirupathur","Tamil Nadu"],
  ["tiruppur","Tiruppur","Tamil Nadu"],
  ["tiruvallur","Tiruvallur","Tamil Nadu"],
  ["tiruvannamalai","Tiruvannamalai","Tamil Nadu"],
  ["tiruvarur","Tiruvarur","Tamil Nadu"],
  ["vellore","Vellore","Tamil Nadu"],
  ["viluppuram","Viluppuram","Tamil Nadu"],
  ["virudhunagar","Virudhunagar","Tamil Nadu"],
  ["adilabad","Adilabad","Telangana"],
  ["bhadradri-kothagudem","Bhadradri Kothagudem","Telangana"],
  ["hanumakonda","Hanumakonda","Telangana"],
  ["hyderabad","Hyderabad","Telangana"],
  ["jagtial","Jagtial","Telangana"],
  ["jangaon","Jangaon","Telangana"],
  ["jayashankar-bhupalpally","Jayashankar Bhupalpally","Telangana"],
  ["jogulamba-gadwal","Jogulamba Gadwal","Telangana"],
  ["kamareddy","Kamareddy","Telangana"],
  ["karimnagar","Karimnagar","Telangana"],
  ["khammam","Khammam","Telangana"],
  ["komaram-bheem","Komaram Bheem","Telangana"],
  ["mahabubabad","Mahabubabad","Telangana"],
  ["mahabubnagar","Mahabubnagar","Telangana"],
  ["mancherial","Mancherial","Telangana"],
  ["medak","Medak","Telangana"],
  ["medchal-malkajgiri","Medchal Malkajgiri","Telangana"],
  ["mulugu","Mulugu","Telangana"],
  ["nagarkurnool","Nagarkurnool","Telangana"],
  ["nalgonda","Nalgonda","Telangana"],
  ["narayanpet","Narayanpet","Telangana"],
  ["nirmal","Nirmal","Telangana"],
  ["nizamabad","Nizamabad","Telangana"],
  ["peddapalli","Peddapalli","Telangana"],
  ["rajanna-sircilla","Rajanna Sircilla","Telangana"],
  ["rangareddy","Rangareddy","Telangana"],
  ["sangareddy","Sangareddy","Telangana"],
  ["siddipet","Siddipet","Telangana"],
  ["suryapet","Suryapet","Telangana"],
  ["vikarabad","Vikarabad","Telangana"],
  ["wanaparthy","Wanaparthy","Telangana"],
  ["warangal","Warangal","Telangana"],
  ["yadadri-bhuvanagiri","Yadadri Bhuvanagiri","Telangana"],
  ["dhalai","Dhalai","Tripura"],
  ["gomati","Gomati","Tripura"],
  ["khowai","Khowai","Tripura"],
  ["north-tripura","North Tripura","Tripura"],
  ["sepahijala","Sepahijala","Tripura"],
  ["south-tripura","South Tripura","Tripura"],
  ["unakoti","Unakoti","Tripura"],
  ["west-tripura","West Tripura","Tripura"],
  ["agra","Agra","Uttar Pradesh"],
  ["aligarh","Aligarh","Uttar Pradesh"],
  ["prayagraj","Prayagraj","Uttar Pradesh"],
  ["ambedkar-nagar","Ambedkar Nagar","Uttar Pradesh"],
  ["amethi","Amethi","Uttar Pradesh"],
  ["amroha","Amroha","Uttar Pradesh"],
  ["auraiya","Auraiya","Uttar Pradesh"],
  ["ayodhya","Ayodhya","Uttar Pradesh"],
  ["azamgarh","Azamgarh","Uttar Pradesh"],
  ["baghpat","Baghpat","Uttar Pradesh"],
  ["bahraich","Bahraich","Uttar Pradesh"],
  ["ballia","Ballia","Uttar Pradesh"],
  ["banda","Banda","Uttar Pradesh"],
  ["barabanki","Barabanki","Uttar Pradesh"],
  ["bareilly","Bareilly","Uttar Pradesh"],
  ["basti","Basti","Uttar Pradesh"],
  ["bhadohi","Bhadohi","Uttar Pradesh"],
  ["bijnor","Bijnor","Uttar Pradesh"],
  ["budaun","Budaun","Uttar Pradesh"],
  ["bulandshahr","Bulandshahr","Uttar Pradesh"],
  ["chandauli","Chandauli","Uttar Pradesh"],
  ["chitrakoot","Chitrakoot","Uttar Pradesh"],
  ["deoria","Deoria","Uttar Pradesh"],
  ["etah","Etah","Uttar Pradesh"],
  ["etawah","Etawah","Uttar Pradesh"],
  ["farrukhabad","Farrukhabad","Uttar Pradesh"],
  ["fatehpur","Fatehpur","Uttar Pradesh"],
  ["firozabad","Firozabad","Uttar Pradesh"],
  ["gautam-buddha-nagar","Gautam Buddha Nagar","Uttar Pradesh"],
  ["ghaziabad","Ghaziabad","Uttar Pradesh"],
  ["ghazipur","Ghazipur","Uttar Pradesh"],
  ["gonda","Gonda","Uttar Pradesh"],
  ["gorakhpur","Gorakhpur","Uttar Pradesh"],
  ["hamirpur-up","Hamirpur","Uttar Pradesh"],
  ["hapur","Hapur","Uttar Pradesh"],
  ["hardoi","Hardoi","Uttar Pradesh"],
  ["hathras","Hathras","Uttar Pradesh"],
  ["jalaun","Jalaun","Uttar Pradesh"],
  ["jaunpur","Jaunpur","Uttar Pradesh"],
  ["jhansi","Jhansi","Uttar Pradesh"],
  ["kannauj","Kannauj","Uttar Pradesh"],
  ["kanpur-dehat","Kanpur Dehat","Uttar Pradesh"],
  ["kanpur-nagar","Kanpur Nagar","Uttar Pradesh"],
  ["kasganj","Kasganj","Uttar Pradesh"],
  ["kaushambi","Kaushambi","Uttar Pradesh"],
  ["kheri","Kheri","Uttar Pradesh"],
  ["kushinagar","Kushinagar","Uttar Pradesh"],
  ["lalitpur","Lalitpur","Uttar Pradesh"],
  ["lucknow","Lucknow","Uttar Pradesh"],
  ["maharajganj","Maharajganj","Uttar Pradesh"],
  ["mahoba","Mahoba","Uttar Pradesh"],
  ["mainpuri","Mainpuri","Uttar Pradesh"],
  ["mathura","Mathura","Uttar Pradesh"],
  ["mau","Mau","Uttar Pradesh"],
  ["meerut","Meerut","Uttar Pradesh"],
  ["mirzapur","Mirzapur","Uttar Pradesh"],
  ["moradabad","Moradabad","Uttar Pradesh"],
  ["muzaffarnagar","Muzaffarnagar","Uttar Pradesh"],
  ["noida","Noida","Uttar Pradesh"],
  ["pilibhit","Pilibhit","Uttar Pradesh"],
  ["pratapgarh-up","Pratapgarh","Uttar Pradesh"],
  ["raebareli","Raebareli","Uttar Pradesh"],
  ["rampur","Rampur","Uttar Pradesh"],
  ["saharanpur","Saharanpur","Uttar Pradesh"],
  ["sambhal","Sambhal","Uttar Pradesh"],
  ["sant-kabir-nagar","Sant Kabir Nagar","Uttar Pradesh"],
  ["shahjahanpur","Shahjahanpur","Uttar Pradesh"],
  ["shamli","Shamli","Uttar Pradesh"],
  ["shravasti","Shravasti","Uttar Pradesh"],
  ["siddharthnagar","Siddharthnagar","Uttar Pradesh"],
  ["sitapur","Sitapur","Uttar Pradesh"],
  ["sonbhadra","Sonbhadra","Uttar Pradesh"],
  ["sultanpur","Sultanpur","Uttar Pradesh"],
  ["unnao","Unnao","Uttar Pradesh"],
  ["varanasi","Varanasi","Uttar Pradesh"],
  ["almora","Almora","Uttarakhand"],
  ["bageshwar","Bageshwar","Uttarakhand"],
  ["chamoli","Chamoli","Uttarakhand"],
  ["champawat","Champawat","Uttarakhand"],
  ["dehradun","Dehradun","Uttarakhand"],
  ["haridwar","Haridwar","Uttarakhand"],
  ["nainital","Nainital","Uttarakhand"],
  ["pauri-garhwal","Pauri Garhwal","Uttarakhand"],
  ["pithoragarh","Pithoragarh","Uttarakhand"],
  ["rudraprayag","Rudraprayag","Uttarakhand"],
  ["tehri-garhwal","Tehri Garhwal","Uttarakhand"],
  ["udham-singh-nagar","Udham Singh Nagar","Uttarakhand"],
  ["uttarkashi","Uttarkashi","Uttarakhand"],
  ["alipurduar","Alipurduar","West Bengal"],
  ["bankura","Bankura","West Bengal"],
  ["birbhum","Birbhum","West Bengal"],
  ["cooch-behar","Cooch Behar","West Bengal"],
  ["dakshin-dinajpur","Dakshin Dinajpur","West Bengal"],
  ["darjeeling","Darjeeling","West Bengal"],
  ["hooghly","Hooghly","West Bengal"],
  ["howrah","Howrah","West Bengal"],
  ["jalpaiguri","Jalpaiguri","West Bengal"],
  ["jhargram","Jhargram","West Bengal"],
  ["kalimpong","Kalimpong","West Bengal"],
  ["kolkata","Kolkata","West Bengal"],
  ["malda","Malda","West Bengal"],
  ["murshidabad","Murshidabad","West Bengal"],
  ["nadia","Nadia","West Bengal"],
  ["north-24-parganas","North 24 Parganas","West Bengal"],
  ["paschim-bardhaman","Paschim Bardhaman","West Bengal"],
  ["paschim-medinipur","Paschim Medinipur","West Bengal"],
  ["purba-bardhaman","Purba Bardhaman","West Bengal"],
  ["purba-medinipur","Purba Medinipur","West Bengal"],
  ["purulia","Purulia","West Bengal"],
  ["south-24-parganas","South 24 Parganas","West Bengal"],
  ["uttar-dinajpur","Uttar Dinajpur","West Bengal"],
  ["delhi","Delhi","Delhi"],
  ["new-delhi","New Delhi","Delhi"],
  ["chandigarh","Chandigarh","Chandigarh"],
  ["puducherry","Puducherry","Puducherry"],
  ["karaikal","Karaikal","Puducherry"],
  ["mahe","Mahe","Puducherry"],
  ["yanam","Yanam","Puducherry"],
  ["daman","Daman","Dadra & Nagar Haveli and Daman & Diu"],
  ["diu","Diu","Dadra & Nagar Haveli and Daman & Diu"],
  ["dadra","Dadra & Nagar Haveli","Dadra & Nagar Haveli and Daman & Diu"],
  ["lakshadweep","Lakshadweep","Lakshadweep"],
  ["port-blair","Port Blair","Andaman & Nicobar Islands"],
  ["srinagar","Srinagar","Jammu & Kashmir"],
  ["jammu","Jammu","Jammu & Kashmir"],
  ["anantnag","Anantnag","Jammu & Kashmir"],
  ["baramulla","Baramulla","Jammu & Kashmir"],
  ["budgam","Budgam","Jammu & Kashmir"],
  ["bandipora","Bandipora","Jammu & Kashmir"],
  ["ganderbal","Ganderbal","Jammu & Kashmir"],
  ["kulgam","Kulgam","Jammu & Kashmir"],
  ["kupwara","Kupwara","Jammu & Kashmir"],
  ["pulwama","Pulwama","Jammu & Kashmir"],
  ["rajouri","Rajouri","Jammu & Kashmir"],
  ["ramban","Ramban","Jammu & Kashmir"],
  ["reasi","Reasi","Jammu & Kashmir"],
  ["samba","Samba","Jammu & Kashmir"],
  ["shopian","Shopian","Jammu & Kashmir"],
  ["udhampur","Udhampur","Jammu & Kashmir"],
  ["kathua","Kathua","Jammu & Kashmir"],
  ["doda","Doda","Jammu & Kashmir"],
  ["kishtwar","Kishtwar","Jammu & Kashmir"],
  ["poonch","Poonch","Jammu & Kashmir"],
  ["leh","Leh","Ladakh"],
  ["kargil","Kargil","Ladakh"],
];

// ==================== STATIC PAGES ====================
const staticPages = [
  { loc: '/', priority: '1.00', changefreq: 'weekly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/products', priority: '0.95', changefreq: 'weekly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/products/school-erp', priority: '0.92', changefreq: 'weekly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/products/ozbiz', priority: '0.92', changefreq: 'weekly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/products/clinic', priority: '0.92', changefreq: 'weekly', lastmod: '2026-05-31' },
  { loc: '/products/frugano', priority: '0.92', changefreq: 'weekly', lastmod: '2026-05-31' },
  { loc: '/services', priority: '0.90', changefreq: 'weekly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/blog', priority: '0.90', changefreq: 'weekly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/work', priority: '0.80', changefreq: 'monthly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/pricing', priority: '0.80', changefreq: 'monthly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/about', priority: '0.70', changefreq: 'monthly', lastmod: new Date().toISOString().split('T')[0] },
  { loc: '/contact', priority: '0.70', changefreq: 'monthly', lastmod: new Date().toISOString().split('T')[0] },
];

// ==================== BLOG POSTS (1-17) ====================
const blogPosts = [];
for (let i = 1; i <= 17; i++) {
  blogPosts.push({
    loc: `/blog/${i}`,
    priority: '0.85',
    changefreq: 'weekly',
    lastmod: '2026-05-31'
  });
}

// ==================== CITY PAGES ====================
const cityPages = INDIA_LOCATIONS.map(([slug, name]) => ({
  loc: `/cities/${slug}`,
  priority: '0.80',
  changefreq: 'monthly',
  lastmod: new Date().toISOString().split('T')[0]
}));

// ==================== GENERATE SITEMAP ====================
const generateSitemap = () => {
  const allUrls = [...staticPages, ...blogPosts, ...cityPages];
  
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n';
  xml += '  xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"\n';
  xml += '  xmlns:xhtml="http://www.w3.org/1999/xhtml"\n';
  xml += '  xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"\n';
  xml += '  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n';
  
  allUrls.forEach(url => {
    xml += `  <url>\n`;
    xml += `    <loc>https://www.orbnix.in${url.loc}</loc>\n`;
    xml += `    <lastmod>${url.lastmod}</lastmod>\n`;
    xml += `    <changefreq>${url.changefreq}</changefreq>\n`;
    xml += `    <priority>${url.priority}</priority>\n`;
    xml += `  </url>\n`;
  });
  
  xml += '</urlset>';
  
  // Ensure public directory exists
  const publicDir = resolve(__dirname, 'public');
  if (!existsSync(publicDir)) {
    mkdirSync(publicDir, { recursive: true });
  }
  
  // Write sitemap.xml to public folder
  const sitemapPath = resolve(publicDir, 'sitemap.xml');
  writeFileSync(sitemapPath, xml);
  
  console.log(`✅ Sitemap generated successfully!`);
  console.log(`   📍 Total URLs: ${allUrls.length}`);
  console.log(`   📄 Static pages: ${staticPages.length}`);
  console.log(`   📝 Blog posts: ${blogPosts.length}`);
  console.log(`   🏙️  City pages: ${cityPages.length}`);
  console.log(`   💾 Saved to: ${sitemapPath}`);
};

// ==================== RUN ====================
generateSitemap();